spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://172.23.62.176:3306/ziyuan?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8999